/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author toby
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
        scenePanel.init(menuPanel);
        menuPanel.init(scenePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scenePanel = new ScenePanel();
        menuPanel = new MenuPanel();
        num_col_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        num_row_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        emptyButton = new javax.swing.JButton();
        tableButton = new javax.swing.JButton();
        seatButton = new javax.swing.JButton();
        wallButton = new javax.swing.JButton();
        recyclableButton = new javax.swing.JButton();
        trashButton = new javax.swing.JButton();
        drinkButton = new javax.swing.JButton();
        foodButton = new javax.swing.JButton();
        personButton = new javax.swing.JButton();
        parkingButton = new javax.swing.JButton();
        nomeFileField = new javax.swing.JTextField();
        exportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SceneGenerator");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        scenePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scenePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout scenePanelLayout = new javax.swing.GroupLayout(scenePanel);
        scenePanel.setLayout(scenePanelLayout);
        scenePanelLayout.setHorizontalGroup(
            scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        scenePanelLayout.setVerticalGroup(
            scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );

        getContentPane().add(scenePanel);

        num_col_field.setText("5");
        num_col_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_col_fieldActionPerformed(evt);
            }
        });

        jLabel2.setText("x");

        num_row_field.setText("5");
        num_row_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_row_fieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Dimensioni griglia");

        updateButton.setText("Aggiorna");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Inserisci");

        emptyButton.setText("Vuoto");
        emptyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyButtonActionPerformed(evt);
            }
        });

        tableButton.setText("Tavolo");
        tableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableButtonActionPerformed(evt);
            }
        });

        seatButton.setText("Sedia");
        seatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatButtonActionPerformed(evt);
            }
        });

        wallButton.setText("Muro");
        wallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wallButtonActionPerformed(evt);
            }
        });

        recyclableButton.setText("Riciclabile");
        recyclableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recyclableButtonActionPerformed(evt);
            }
        });

        trashButton.setText("Cestino");
        trashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trashButtonActionPerformed(evt);
            }
        });

        drinkButton.setText("Dispenser drink");
        drinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkButtonActionPerformed(evt);
            }
        });

        foodButton.setText("Dispenser cibo");
        foodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodButtonActionPerformed(evt);
            }
        });

        personButton.setText("Persona");
        personButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personButtonActionPerformed(evt);
            }
        });

        parkingButton.setText("Parcheggio");
        parkingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkingButtonActionPerformed(evt);
            }
        });

        nomeFileField.setText("initMap");
        nomeFileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFileFieldActionPerformed(evt);
            }
        });

        exportButton.setText("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(num_row_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num_col_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updateButton)
                            .addComponent(jLabel3)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(emptyButton)
                                .addGap(10, 10, 10)
                                .addComponent(wallButton))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(seatButton)
                                .addGap(10, 10, 10)
                                .addComponent(tableButton))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(recyclableButton)
                                .addGap(10, 10, 10)
                                .addComponent(trashButton))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(foodButton)
                                .addGap(10, 10, 10)
                                .addComponent(drinkButton))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(personButton)
                                .addGap(10, 10, 10)
                                .addComponent(parkingButton))))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exportButton)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(nomeFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num_col_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_row_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateButton)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emptyButton)
                    .addComponent(wallButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatButton)
                    .addComponent(tableButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recyclableButton)
                    .addComponent(trashButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodButton)
                    .addComponent(drinkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personButton)
                    .addComponent(parkingButton))
                .addGap(40, 40, 40)
                .addComponent(nomeFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportButton)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scenePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scenePanelMouseClicked
        int state = menuPanel.getState();

        int x = (int) evt.getPoint().getX();
        int y = (int) evt.getPoint().getY();
    }//GEN-LAST:event_scenePanelMouseClicked

    private void tableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed
        menuPanel.setState(3);
    }//GEN-LAST:event_tableButtonActionPerformed

    private void emptyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyButtonActionPerformed
        menuPanel.setState(0);
    }//GEN-LAST:event_emptyButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int num_row = Integer.parseInt(num_row_field.getText());
        int num_col = Integer.parseInt(num_col_field.getText());
        if (num_row > 0 && num_col > 0) {
            scenePanel.resizeScene(num_row, num_col);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void num_row_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_row_fieldActionPerformed

    }//GEN-LAST:event_num_row_fieldActionPerformed

    private void num_col_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_col_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_col_fieldActionPerformed

    private void wallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wallButtonActionPerformed
        menuPanel.setState(1);
    }//GEN-LAST:event_wallButtonActionPerformed

    private void seatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatButtonActionPerformed
        menuPanel.setState(2);
    }//GEN-LAST:event_seatButtonActionPerformed

    private void nomeFileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFileFieldActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        scenePanel.exportScene(nomeFileField.getText());
    }//GEN-LAST:event_exportButtonActionPerformed

    private void parkingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkingButtonActionPerformed
        menuPanel.setState(9);
    }//GEN-LAST:event_parkingButtonActionPerformed

    private void personButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personButtonActionPerformed
        menuPanel.setState(8);
    }//GEN-LAST:event_personButtonActionPerformed

    private void drinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkButtonActionPerformed
        menuPanel.setState(7);
    }//GEN-LAST:event_drinkButtonActionPerformed

    private void foodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodButtonActionPerformed
        menuPanel.setState(6);
    }//GEN-LAST:event_foodButtonActionPerformed

    private void trashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trashButtonActionPerformed
        menuPanel.setState(5);
    }//GEN-LAST:event_trashButtonActionPerformed

    private void recyclableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recyclableButtonActionPerformed
        menuPanel.setState(4);
    }//GEN-LAST:event_recyclableButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drinkButton;
    private javax.swing.JButton emptyButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton foodButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private MenuPanel menuPanel;
    private javax.swing.JTextField nomeFileField;
    private javax.swing.JTextField num_col_field;
    private javax.swing.JTextField num_row_field;
    private javax.swing.JButton parkingButton;
    private javax.swing.JButton personButton;
    private javax.swing.JButton recyclableButton;
    private ScenePanel scenePanel;
    private javax.swing.JButton seatButton;
    private javax.swing.JButton tableButton;
    private javax.swing.JButton trashButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton wallButton;
    // End of variables declaration//GEN-END:variables
}
