
import java.awt.Graphics;
import java.awt.Graphics2D;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author toby
 */
public class ScenePanel extends javax.swing.JPanel {

    private MenuPanel menuPanel;

    /**
     * Creates new form ScenePanel
     */
    public ScenePanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        System.out.println(this.getWidth() + " " + this.getHeight());
        super.paintComponent(g); // call superclass's paintComponent  

        Graphics2D g2 = (Graphics2D) g; // cast g to Graphics2D  

        if (s != null) {
            s.drawScene(g2);
        }
    }

    Scene s;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void init(MenuPanel menuPanel) {
        s = new Scene(5, 5, this.getWidth(), this.getHeight());
        this.menuPanel = menuPanel;
    }

    void resizeScene(int num_x, int num_y) {
        s.resize(num_x, num_y);
        repaint();
    }

    void exportScene(String text) {
        String textFile = s.exportScene();
        // TODO scrivere scrittura su file di textFile
    }
}
