(clear)
(load "1_main.clp")
(load "2_env.clp")
(load "2_env_creation.clp")
(load "2_env_messaging.clp")
(load "2_env_agentoperations.clp")
(load "2_env_agentmovements.clp")
(load "3_agent.clp")
(reset)
